package com.keyservice.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.LocalDateTime;

/**
 * JPA entity representing a persisted UUID, stored in the {@code uuid_log} table.
 *
 * <p>Each row records a UUID generated by the {@code GET /uuid} endpoint together
 * with the timestamp at which it was created.</p>
 */
@Entity
@Table(name = "uuid_log")
public class UuidEntry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true)
    private String uuid;

    @Column(nullable = false)
    private LocalDateTime createdAt;

    /**
     * No-arg constructor required by the JPA specification.
     * Not intended for direct use by application code.
     */
    protected UuidEntry() {}

    /**
     * Creates a new entry with the given UUID and creation timestamp.
     *
     * @param uuid      the UUID string to persist; must be unique across all rows
     * @param createdAt the point in time at which the UUID was generated
     */
    public UuidEntry(String uuid, LocalDateTime createdAt) {
        this.uuid = uuid;
        this.createdAt = createdAt;
    }

    /**
     * Returns the auto-generated primary key.
     *
     * @return the database-assigned identifier, or {@code null} before the entity is persisted
     */
    public Long getId()              { return id; }

    /**
     * Returns the persisted UUID string.
     *
     * @return the UUID value
     */
    public String getUuid()          { return uuid; }

    /**
     * Returns the timestamp recorded when this UUID was generated.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() { return createdAt; }
}